// data/products.js

export const products = [
  {
    name: 'Tomato',
    price: 30,
    unit: 'kg',
    image: '/images/Tomato.jpg',
    category: 'Vegetables',
    farmer: 'Raju',
    locality: 'Nalgonda',
  },
  {
    name: 'Potato',
    price: 30,
    unit: 'kg',
    image: '/images/Potato.jpg',
    category: 'Vegetables',
    farmer: 'Sita',
    locality: 'Warangal',
  },
  {
    name: 'Onion',
    price: 20,
    unit: 'kg',
    image: '/images/Onion.jpg',
    category: 'Vegetables',
    farmer: 'Lakshman',
    locality: 'Kurnool',
  },
  {
    name: 'Carrot',
    price: 60,
    unit: 'kg',
    image: '/images/Carrot.jpg',
    category: 'Vegetables',
    farmer: 'Meena',
    locality: 'Vijayawada',
  },
  {
    name: 'Cauliflower',
    price: 60,
    unit: 'kg',
    image: '/images/Cauliflower.webp',
    category: 'Vegetables',
    farmer: 'Ramesh',
    locality: 'Tirupati',
  },
  {
    name: 'Brinjal',
    price: 30,
    unit: 'kg',
    image: '/images/Brinjal.jpg',
    category: 'Vegetables',
    farmer: 'Anita',
    locality: 'Kadapa',
  },
  {
    name: 'Spinach',
    price: 20,
    unit: 'bundle',
    image: '/images/Spinach.webp',
    category: 'Vegetables',
    farmer: 'Prakash',
    locality: 'Guntur',
  },
  {
    name: 'Cabbage',
    price: 20,
    unit: 'kg',
    image: '/images/Cabbage.jpg',
    category: 'Vegetables',
    farmer: 'Sundar',
    locality: 'Rajahmundry',
  },
  {
    name: 'Peas',
    price: 105,
    unit: 'kg',
    image: '/images/Peas.webp',
    category: 'Vegetables',
    farmer: 'Radha',
    locality: 'Vizag',
  },
  {
    name: 'Radish',
    price: 40,
    unit: 'kg',
    image: '/images/Raddish.webp',
    category: 'Vegetables',
    farmer: 'Vikram',
    locality: 'Anantapur',
  },
  {
    name: 'Pumpkin',
    price: 120,
    unit: 'kg',
    image: '/images/Pumpkin.jpg',
    category: 'Vegetables',
    farmer: 'Lakshmi',
    locality: 'Khammam',
  },
  {
    name: 'Bottle Gourd',
    price: 30,
    unit: 'kg',
    image: '/images/Bottlegourd.webp',
    category: 'Vegetables',
    farmer: 'Suresh',
    locality: 'Nellore',
  },
  {
    name: 'Bitter Gourd',
    price: 60,
    unit: 'kg',
    image: '/images/Bittergourd.jpg',
    category: 'Vegetables',
    farmer: 'Geetha',
    locality: 'Kakinada',
  },
  {
    name: 'Okra',
    price: 60,
    unit: 'kg',
    image: '/images/Okra.avif',
    category: 'Vegetables',
    farmer: 'Manoj',
    locality: 'Eluru',
  },
  {
    name: 'Sweet Corn',
    price: 20,
    unit: 'bundle',
    image: '/images/Sweetcorn.webp',
    category: 'Vegetables',
    farmer: 'Bhavani',
    locality: 'Chittoor',
  },
  {
    name: 'Green Beans',
    price: 60,
    unit: 'kg',
    image: '/images/GreenBeans.jpg',
    category: 'Vegetables',
    farmer: 'Sanjay',
    locality: 'Adilabad',
  },
  {
    name: 'Garlic',
    price: 400,
    unit: 'kg',
    image: '/images/Garlic.jpg',
    category: 'Vegetables',
    farmer: 'Meena',
    locality: 'Medak',
  },
  {
    name: 'Ginger',
    price: 120,
    unit: 'kg',
    image: '/images/Ginger.jpg',
    category: 'Vegetables',
    farmer: 'Ravi',
    locality: 'Nizamabad',
  },
  {
    name: 'Chili',
    price: 80,
    unit: 'kg',
    image: '/images/Chili.jpg',
    category: 'Vegetables',
    farmer: 'Kiran',
    locality: 'Mahbubnagar',
  },
  {
    name: 'Cucumber',
    price: 60,
    unit: 'kg',
    image: '/images/Cucumber.jpg',
    category: 'Vegetables',
    farmer: 'Swapna',
    locality: 'Srikakulam',
  },
  {
    name: 'Apple',
    price: 30,
    unit: 'pcs',
    image: '/images/Apple.webp',
    category: 'Fruits',
    farmer: 'John',
    locality: 'Shimla',
  },
  {
    name: 'Banana',
    price: 60,
    unit: 'dozen',
    image: '/images/Bannana.jpg',
    category: 'Fruits',
    farmer: 'Priya',
    locality: 'Nashik',
  },
  {
    name: 'Mango',
    price: 30,
    unit: 'pcs',
    image: '/images/Mango.webp',
    category: 'Fruits',
    farmer: 'Anil',
    locality: 'Ratnagiri',
  },
  {
    name: 'Pineapple',
    price: 40,
    unit: 'pcs',
    image: '/images/Pineapple.webp',
    category: 'Fruits',
    farmer: 'Mary',
    locality: 'Kerala',
  },
  {
    name: 'Papaya',
    price: 40,
    unit: 'pcs',
    image: '/images/Papaya.jpg',
    category: 'Fruits',
    farmer: 'Kumar',
    locality: 'Coimbatore',
  },
  {
    name: 'Grapes',
    price: 100,
    unit: 'kg',
    image: '/images/Grapes.webp',
    category: 'Fruits',
    farmer: 'Sonal',
    locality: 'Nasik',
  },
  {
    name: 'Watermelon',
    price: 60,
    unit: 'pcs',
    image: '/images/Watermelon.webp',
    category: 'Fruits',
    farmer: 'Deepak',
    locality: 'Punjab',
  },
  {
    name: 'Orange',
    price: 110,
    unit: 'pcs',
    image: '/images/Orange.webp',
    category: 'Fruits',
    farmer: 'Sneha',
    locality: 'Nagpur',
  },
  {
    name: 'Lemon',
    price: 5,
    unit: 'pcs',
    image: '/images/Lemon.jpg',
    category: 'Fruits',
    farmer: 'Rajesh',
    locality: 'Madurai',
  },
  {
    name: 'Guava',
    price: 30,
    unit: 'pcs',
    image: '/images/Guava.webp',
    category: 'Fruits',
    farmer: 'Rekha',
    locality: 'Mysore',
  },
];
